// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Actor.proto

package com.game.protocol;

public final class ActorProtocol {
  private ActorProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MonsterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Monster)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 level = 3;</code>
     * @return The level.
     */
    int getLevel();

    /**
     * <code>int32 state = 4;</code>
     * @return The state.
     */
    int getState();

    /**
     * <code>.Property property = 5;</code>
     * @return Whether the property field is set.
     */
    boolean hasProperty();
    /**
     * <code>.Property property = 5;</code>
     * @return The property.
     */
    com.game.protocol.CommonProtocol.Property getProperty();
    /**
     * <code>.Property property = 5;</code>
     */
    com.game.protocol.CommonProtocol.PropertyOrBuilder getPropertyOrBuilder();
  }
  /**
   * Protobuf type {@code Monster}
   */
  public  static final class Monster extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Monster)
      MonsterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Monster.newBuilder() to construct.
    private Monster(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Monster() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Monster();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Monster(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              level_ = input.readInt32();
              break;
            }
            case 32: {

              state_ = input.readInt32();
              break;
            }
            case 42: {
              com.game.protocol.CommonProtocol.Property.Builder subBuilder = null;
              if (property_ != null) {
                subBuilder = property_.toBuilder();
              }
              property_ = input.readMessage(com.game.protocol.CommonProtocol.Property.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(property_);
                property_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.protocol.ActorProtocol.internal_static_Monster_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.protocol.ActorProtocol.internal_static_Monster_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.protocol.ActorProtocol.Monster.class, com.game.protocol.ActorProtocol.Monster.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    /**
     * <code>int32 level = 3;</code>
     * @return The level.
     */
    public int getLevel() {
      return level_;
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private int state_;
    /**
     * <code>int32 state = 4;</code>
     * @return The state.
     */
    public int getState() {
      return state_;
    }

    public static final int PROPERTY_FIELD_NUMBER = 5;
    private com.game.protocol.CommonProtocol.Property property_;
    /**
     * <code>.Property property = 5;</code>
     * @return Whether the property field is set.
     */
    public boolean hasProperty() {
      return property_ != null;
    }
    /**
     * <code>.Property property = 5;</code>
     * @return The property.
     */
    public com.game.protocol.CommonProtocol.Property getProperty() {
      return property_ == null ? com.game.protocol.CommonProtocol.Property.getDefaultInstance() : property_;
    }
    /**
     * <code>.Property property = 5;</code>
     */
    public com.game.protocol.CommonProtocol.PropertyOrBuilder getPropertyOrBuilder() {
      return getProperty();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (level_ != 0) {
        output.writeInt32(3, level_);
      }
      if (state_ != 0) {
        output.writeInt32(4, state_);
      }
      if (property_ != null) {
        output.writeMessage(5, getProperty());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, level_);
      }
      if (state_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, state_);
      }
      if (property_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getProperty());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.protocol.ActorProtocol.Monster)) {
        return super.equals(obj);
      }
      com.game.protocol.ActorProtocol.Monster other = (com.game.protocol.ActorProtocol.Monster) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getLevel()
          != other.getLevel()) return false;
      if (getState()
          != other.getState()) return false;
      if (hasProperty() != other.hasProperty()) return false;
      if (hasProperty()) {
        if (!getProperty()
            .equals(other.getProperty())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState();
      if (hasProperty()) {
        hash = (37 * hash) + PROPERTY_FIELD_NUMBER;
        hash = (53 * hash) + getProperty().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.protocol.ActorProtocol.Monster parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.ActorProtocol.Monster parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.ActorProtocol.Monster parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.ActorProtocol.Monster parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.ActorProtocol.Monster parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.ActorProtocol.Monster parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.ActorProtocol.Monster parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.ActorProtocol.Monster parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.ActorProtocol.Monster parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.protocol.ActorProtocol.Monster parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.ActorProtocol.Monster parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.ActorProtocol.Monster parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.protocol.ActorProtocol.Monster prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Monster}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Monster)
        com.game.protocol.ActorProtocol.MonsterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.protocol.ActorProtocol.internal_static_Monster_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.protocol.ActorProtocol.internal_static_Monster_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.protocol.ActorProtocol.Monster.class, com.game.protocol.ActorProtocol.Monster.Builder.class);
      }

      // Construct using com.game.protocol.ActorProtocol.Monster.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        level_ = 0;

        state_ = 0;

        if (propertyBuilder_ == null) {
          property_ = null;
        } else {
          property_ = null;
          propertyBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.protocol.ActorProtocol.internal_static_Monster_descriptor;
      }

      @java.lang.Override
      public com.game.protocol.ActorProtocol.Monster getDefaultInstanceForType() {
        return com.game.protocol.ActorProtocol.Monster.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.protocol.ActorProtocol.Monster build() {
        com.game.protocol.ActorProtocol.Monster result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.protocol.ActorProtocol.Monster buildPartial() {
        com.game.protocol.ActorProtocol.Monster result = new com.game.protocol.ActorProtocol.Monster(this);
        result.id_ = id_;
        result.name_ = name_;
        result.level_ = level_;
        result.state_ = state_;
        if (propertyBuilder_ == null) {
          result.property_ = property_;
        } else {
          result.property_ = propertyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.protocol.ActorProtocol.Monster) {
          return mergeFrom((com.game.protocol.ActorProtocol.Monster)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.protocol.ActorProtocol.Monster other) {
        if (other == com.game.protocol.ActorProtocol.Monster.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (other.getState() != 0) {
          setState(other.getState());
        }
        if (other.hasProperty()) {
          mergeProperty(other.getProperty());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.protocol.ActorProtocol.Monster parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.protocol.ActorProtocol.Monster) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>int32 level = 3;</code>
       * @return The level.
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>int32 level = 3;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 level = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <code>int32 state = 4;</code>
       * @return The state.
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>int32 state = 4;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 state = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private com.game.protocol.CommonProtocol.Property property_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.game.protocol.CommonProtocol.Property, com.game.protocol.CommonProtocol.Property.Builder, com.game.protocol.CommonProtocol.PropertyOrBuilder> propertyBuilder_;
      /**
       * <code>.Property property = 5;</code>
       * @return Whether the property field is set.
       */
      public boolean hasProperty() {
        return propertyBuilder_ != null || property_ != null;
      }
      /**
       * <code>.Property property = 5;</code>
       * @return The property.
       */
      public com.game.protocol.CommonProtocol.Property getProperty() {
        if (propertyBuilder_ == null) {
          return property_ == null ? com.game.protocol.CommonProtocol.Property.getDefaultInstance() : property_;
        } else {
          return propertyBuilder_.getMessage();
        }
      }
      /**
       * <code>.Property property = 5;</code>
       */
      public Builder setProperty(com.game.protocol.CommonProtocol.Property value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          property_ = value;
          onChanged();
        } else {
          propertyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Property property = 5;</code>
       */
      public Builder setProperty(
          com.game.protocol.CommonProtocol.Property.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          property_ = builderForValue.build();
          onChanged();
        } else {
          propertyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Property property = 5;</code>
       */
      public Builder mergeProperty(com.game.protocol.CommonProtocol.Property value) {
        if (propertyBuilder_ == null) {
          if (property_ != null) {
            property_ =
              com.game.protocol.CommonProtocol.Property.newBuilder(property_).mergeFrom(value).buildPartial();
          } else {
            property_ = value;
          }
          onChanged();
        } else {
          propertyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Property property = 5;</code>
       */
      public Builder clearProperty() {
        if (propertyBuilder_ == null) {
          property_ = null;
          onChanged();
        } else {
          property_ = null;
          propertyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Property property = 5;</code>
       */
      public com.game.protocol.CommonProtocol.Property.Builder getPropertyBuilder() {
        
        onChanged();
        return getPropertyFieldBuilder().getBuilder();
      }
      /**
       * <code>.Property property = 5;</code>
       */
      public com.game.protocol.CommonProtocol.PropertyOrBuilder getPropertyOrBuilder() {
        if (propertyBuilder_ != null) {
          return propertyBuilder_.getMessageOrBuilder();
        } else {
          return property_ == null ?
              com.game.protocol.CommonProtocol.Property.getDefaultInstance() : property_;
        }
      }
      /**
       * <code>.Property property = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.game.protocol.CommonProtocol.Property, com.game.protocol.CommonProtocol.Property.Builder, com.game.protocol.CommonProtocol.PropertyOrBuilder> 
          getPropertyFieldBuilder() {
        if (propertyBuilder_ == null) {
          propertyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.game.protocol.CommonProtocol.Property, com.game.protocol.CommonProtocol.Property.Builder, com.game.protocol.CommonProtocol.PropertyOrBuilder>(
                  getProperty(),
                  getParentForChildren(),
                  isClean());
          property_ = null;
        }
        return propertyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Monster)
    }

    // @@protoc_insertion_point(class_scope:Monster)
    private static final com.game.protocol.ActorProtocol.Monster DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.protocol.ActorProtocol.Monster();
    }

    public static com.game.protocol.ActorProtocol.Monster getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Monster>
        PARSER = new com.google.protobuf.AbstractParser<Monster>() {
      @java.lang.Override
      public Monster parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Monster(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Monster> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Monster> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.protocol.ActorProtocol.Monster getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NpcOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Npc)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 level = 3;</code>
     * @return The level.
     */
    int getLevel();

    /**
     * <code>int32 state = 4;</code>
     * @return The state.
     */
    int getState();

    /**
     * <code>.Property property = 5;</code>
     * @return Whether the property field is set.
     */
    boolean hasProperty();
    /**
     * <code>.Property property = 5;</code>
     * @return The property.
     */
    com.game.protocol.CommonProtocol.Property getProperty();
    /**
     * <code>.Property property = 5;</code>
     */
    com.game.protocol.CommonProtocol.PropertyOrBuilder getPropertyOrBuilder();
  }
  /**
   * Protobuf type {@code Npc}
   */
  public  static final class Npc extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Npc)
      NpcOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Npc.newBuilder() to construct.
    private Npc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Npc() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Npc();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Npc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              level_ = input.readInt32();
              break;
            }
            case 32: {

              state_ = input.readInt32();
              break;
            }
            case 42: {
              com.game.protocol.CommonProtocol.Property.Builder subBuilder = null;
              if (property_ != null) {
                subBuilder = property_.toBuilder();
              }
              property_ = input.readMessage(com.game.protocol.CommonProtocol.Property.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(property_);
                property_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.protocol.ActorProtocol.internal_static_Npc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.protocol.ActorProtocol.internal_static_Npc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.protocol.ActorProtocol.Npc.class, com.game.protocol.ActorProtocol.Npc.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVEL_FIELD_NUMBER = 3;
    private int level_;
    /**
     * <code>int32 level = 3;</code>
     * @return The level.
     */
    public int getLevel() {
      return level_;
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private int state_;
    /**
     * <code>int32 state = 4;</code>
     * @return The state.
     */
    public int getState() {
      return state_;
    }

    public static final int PROPERTY_FIELD_NUMBER = 5;
    private com.game.protocol.CommonProtocol.Property property_;
    /**
     * <code>.Property property = 5;</code>
     * @return Whether the property field is set.
     */
    public boolean hasProperty() {
      return property_ != null;
    }
    /**
     * <code>.Property property = 5;</code>
     * @return The property.
     */
    public com.game.protocol.CommonProtocol.Property getProperty() {
      return property_ == null ? com.game.protocol.CommonProtocol.Property.getDefaultInstance() : property_;
    }
    /**
     * <code>.Property property = 5;</code>
     */
    public com.game.protocol.CommonProtocol.PropertyOrBuilder getPropertyOrBuilder() {
      return getProperty();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (level_ != 0) {
        output.writeInt32(3, level_);
      }
      if (state_ != 0) {
        output.writeInt32(4, state_);
      }
      if (property_ != null) {
        output.writeMessage(5, getProperty());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, level_);
      }
      if (state_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, state_);
      }
      if (property_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getProperty());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.protocol.ActorProtocol.Npc)) {
        return super.equals(obj);
      }
      com.game.protocol.ActorProtocol.Npc other = (com.game.protocol.ActorProtocol.Npc) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getLevel()
          != other.getLevel()) return false;
      if (getState()
          != other.getState()) return false;
      if (hasProperty() != other.hasProperty()) return false;
      if (hasProperty()) {
        if (!getProperty()
            .equals(other.getProperty())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState();
      if (hasProperty()) {
        hash = (37 * hash) + PROPERTY_FIELD_NUMBER;
        hash = (53 * hash) + getProperty().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.protocol.ActorProtocol.Npc parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.ActorProtocol.Npc parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.ActorProtocol.Npc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.ActorProtocol.Npc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.ActorProtocol.Npc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.ActorProtocol.Npc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.ActorProtocol.Npc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.ActorProtocol.Npc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.ActorProtocol.Npc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.protocol.ActorProtocol.Npc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.ActorProtocol.Npc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.ActorProtocol.Npc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.protocol.ActorProtocol.Npc prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Npc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Npc)
        com.game.protocol.ActorProtocol.NpcOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.protocol.ActorProtocol.internal_static_Npc_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.protocol.ActorProtocol.internal_static_Npc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.protocol.ActorProtocol.Npc.class, com.game.protocol.ActorProtocol.Npc.Builder.class);
      }

      // Construct using com.game.protocol.ActorProtocol.Npc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        level_ = 0;

        state_ = 0;

        if (propertyBuilder_ == null) {
          property_ = null;
        } else {
          property_ = null;
          propertyBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.protocol.ActorProtocol.internal_static_Npc_descriptor;
      }

      @java.lang.Override
      public com.game.protocol.ActorProtocol.Npc getDefaultInstanceForType() {
        return com.game.protocol.ActorProtocol.Npc.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.protocol.ActorProtocol.Npc build() {
        com.game.protocol.ActorProtocol.Npc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.protocol.ActorProtocol.Npc buildPartial() {
        com.game.protocol.ActorProtocol.Npc result = new com.game.protocol.ActorProtocol.Npc(this);
        result.id_ = id_;
        result.name_ = name_;
        result.level_ = level_;
        result.state_ = state_;
        if (propertyBuilder_ == null) {
          result.property_ = property_;
        } else {
          result.property_ = propertyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.protocol.ActorProtocol.Npc) {
          return mergeFrom((com.game.protocol.ActorProtocol.Npc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.protocol.ActorProtocol.Npc other) {
        if (other == com.game.protocol.ActorProtocol.Npc.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (other.getState() != 0) {
          setState(other.getState());
        }
        if (other.hasProperty()) {
          mergeProperty(other.getProperty());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.protocol.ActorProtocol.Npc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.protocol.ActorProtocol.Npc) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>int32 level = 3;</code>
       * @return The level.
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>int32 level = 3;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 level = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <code>int32 state = 4;</code>
       * @return The state.
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>int32 state = 4;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 state = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private com.game.protocol.CommonProtocol.Property property_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.game.protocol.CommonProtocol.Property, com.game.protocol.CommonProtocol.Property.Builder, com.game.protocol.CommonProtocol.PropertyOrBuilder> propertyBuilder_;
      /**
       * <code>.Property property = 5;</code>
       * @return Whether the property field is set.
       */
      public boolean hasProperty() {
        return propertyBuilder_ != null || property_ != null;
      }
      /**
       * <code>.Property property = 5;</code>
       * @return The property.
       */
      public com.game.protocol.CommonProtocol.Property getProperty() {
        if (propertyBuilder_ == null) {
          return property_ == null ? com.game.protocol.CommonProtocol.Property.getDefaultInstance() : property_;
        } else {
          return propertyBuilder_.getMessage();
        }
      }
      /**
       * <code>.Property property = 5;</code>
       */
      public Builder setProperty(com.game.protocol.CommonProtocol.Property value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          property_ = value;
          onChanged();
        } else {
          propertyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Property property = 5;</code>
       */
      public Builder setProperty(
          com.game.protocol.CommonProtocol.Property.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          property_ = builderForValue.build();
          onChanged();
        } else {
          propertyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Property property = 5;</code>
       */
      public Builder mergeProperty(com.game.protocol.CommonProtocol.Property value) {
        if (propertyBuilder_ == null) {
          if (property_ != null) {
            property_ =
              com.game.protocol.CommonProtocol.Property.newBuilder(property_).mergeFrom(value).buildPartial();
          } else {
            property_ = value;
          }
          onChanged();
        } else {
          propertyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Property property = 5;</code>
       */
      public Builder clearProperty() {
        if (propertyBuilder_ == null) {
          property_ = null;
          onChanged();
        } else {
          property_ = null;
          propertyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Property property = 5;</code>
       */
      public com.game.protocol.CommonProtocol.Property.Builder getPropertyBuilder() {
        
        onChanged();
        return getPropertyFieldBuilder().getBuilder();
      }
      /**
       * <code>.Property property = 5;</code>
       */
      public com.game.protocol.CommonProtocol.PropertyOrBuilder getPropertyOrBuilder() {
        if (propertyBuilder_ != null) {
          return propertyBuilder_.getMessageOrBuilder();
        } else {
          return property_ == null ?
              com.game.protocol.CommonProtocol.Property.getDefaultInstance() : property_;
        }
      }
      /**
       * <code>.Property property = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.game.protocol.CommonProtocol.Property, com.game.protocol.CommonProtocol.Property.Builder, com.game.protocol.CommonProtocol.PropertyOrBuilder> 
          getPropertyFieldBuilder() {
        if (propertyBuilder_ == null) {
          propertyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.game.protocol.CommonProtocol.Property, com.game.protocol.CommonProtocol.Property.Builder, com.game.protocol.CommonProtocol.PropertyOrBuilder>(
                  getProperty(),
                  getParentForChildren(),
                  isClean());
          property_ = null;
        }
        return propertyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Npc)
    }

    // @@protoc_insertion_point(class_scope:Npc)
    private static final com.game.protocol.ActorProtocol.Npc DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.protocol.ActorProtocol.Npc();
    }

    public static com.game.protocol.ActorProtocol.Npc getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Npc>
        PARSER = new com.google.protobuf.AbstractParser<Npc>() {
      @java.lang.Override
      public Npc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Npc(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Npc> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Npc> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.protocol.ActorProtocol.Npc getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Monster_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Monster_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Npc_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Npc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Actor.proto\032\014Common.proto\"^\n\007Monster\022\n" +
      "\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005level\030\003 \001(\005\022" +
      "\r\n\005state\030\004 \001(\005\022\033\n\010property\030\005 \001(\0132\t.Prope" +
      "rty\"Z\n\003Npc\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r\n\005" +
      "level\030\003 \001(\005\022\r\n\005state\030\004 \001(\005\022\033\n\010property\030\005" +
      " \001(\0132\t.PropertyB\"\n\021com.game.protocolB\rAc" +
      "torProtocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.game.protocol.CommonProtocol.getDescriptor(),
        });
    internal_static_Monster_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Monster_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Monster_descriptor,
        new java.lang.String[] { "Id", "Name", "Level", "State", "Property", });
    internal_static_Npc_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Npc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Npc_descriptor,
        new java.lang.String[] { "Id", "Name", "Level", "State", "Property", });
    com.game.protocol.CommonProtocol.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
