// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bag.proto

package com.game.protocol;

public final class BagProtocol {
  private BagProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OpenBagOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OpenBag)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 bagId = 1;</code>
     * @return The bagId.
     */
    int getBagId();
  }
  /**
   * <pre>
   * 打开背包请求
   * </pre>
   *
   * Protobuf type {@code OpenBag}
   */
  public  static final class OpenBag extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OpenBag)
      OpenBagOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OpenBag.newBuilder() to construct.
    private OpenBag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OpenBag() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OpenBag();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OpenBag(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              bagId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.protocol.BagProtocol.internal_static_OpenBag_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.protocol.BagProtocol.internal_static_OpenBag_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.protocol.BagProtocol.OpenBag.class, com.game.protocol.BagProtocol.OpenBag.Builder.class);
    }

    public static final int BAGID_FIELD_NUMBER = 1;
    private int bagId_;
    /**
     * <code>int32 bagId = 1;</code>
     * @return The bagId.
     */
    public int getBagId() {
      return bagId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bagId_ != 0) {
        output.writeInt32(1, bagId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bagId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bagId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.protocol.BagProtocol.OpenBag)) {
        return super.equals(obj);
      }
      com.game.protocol.BagProtocol.OpenBag other = (com.game.protocol.BagProtocol.OpenBag) obj;

      if (getBagId()
          != other.getBagId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BAGID_FIELD_NUMBER;
      hash = (53 * hash) + getBagId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.protocol.BagProtocol.OpenBag parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.BagProtocol.OpenBag parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.OpenBag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.BagProtocol.OpenBag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.OpenBag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.BagProtocol.OpenBag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.OpenBag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.BagProtocol.OpenBag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.OpenBag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.protocol.BagProtocol.OpenBag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.OpenBag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.BagProtocol.OpenBag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.protocol.BagProtocol.OpenBag prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 打开背包请求
     * </pre>
     *
     * Protobuf type {@code OpenBag}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OpenBag)
        com.game.protocol.BagProtocol.OpenBagOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.protocol.BagProtocol.internal_static_OpenBag_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.protocol.BagProtocol.internal_static_OpenBag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.protocol.BagProtocol.OpenBag.class, com.game.protocol.BagProtocol.OpenBag.Builder.class);
      }

      // Construct using com.game.protocol.BagProtocol.OpenBag.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bagId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.protocol.BagProtocol.internal_static_OpenBag_descriptor;
      }

      @java.lang.Override
      public com.game.protocol.BagProtocol.OpenBag getDefaultInstanceForType() {
        return com.game.protocol.BagProtocol.OpenBag.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.protocol.BagProtocol.OpenBag build() {
        com.game.protocol.BagProtocol.OpenBag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.protocol.BagProtocol.OpenBag buildPartial() {
        com.game.protocol.BagProtocol.OpenBag result = new com.game.protocol.BagProtocol.OpenBag(this);
        result.bagId_ = bagId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.protocol.BagProtocol.OpenBag) {
          return mergeFrom((com.game.protocol.BagProtocol.OpenBag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.protocol.BagProtocol.OpenBag other) {
        if (other == com.game.protocol.BagProtocol.OpenBag.getDefaultInstance()) return this;
        if (other.getBagId() != 0) {
          setBagId(other.getBagId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.protocol.BagProtocol.OpenBag parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.protocol.BagProtocol.OpenBag) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bagId_ ;
      /**
       * <code>int32 bagId = 1;</code>
       * @return The bagId.
       */
      public int getBagId() {
        return bagId_;
      }
      /**
       * <code>int32 bagId = 1;</code>
       * @param value The bagId to set.
       * @return This builder for chaining.
       */
      public Builder setBagId(int value) {
        
        bagId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bagId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBagId() {
        
        bagId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OpenBag)
    }

    // @@protoc_insertion_point(class_scope:OpenBag)
    private static final com.game.protocol.BagProtocol.OpenBag DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.protocol.BagProtocol.OpenBag();
    }

    public static com.game.protocol.BagProtocol.OpenBag getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OpenBag>
        PARSER = new com.google.protobuf.AbstractParser<OpenBag>() {
      @java.lang.Override
      public OpenBag parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OpenBag(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OpenBag> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OpenBag> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.protocol.BagProtocol.OpenBag getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BagInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BagInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 bagId = 1;</code>
     * @return The bagId.
     */
    int getBagId();

    /**
     * <code>string bagName = 2;</code>
     * @return The bagName.
     */
    java.lang.String getBagName();
    /**
     * <code>string bagName = 2;</code>
     * @return The bytes for bagName.
     */
    com.google.protobuf.ByteString
        getBagNameBytes();

    /**
     * <code>repeated .CellInfo cellInfo = 3;</code>
     */
    java.util.List<com.game.protocol.BagProtocol.CellInfo> 
        getCellInfoList();
    /**
     * <code>repeated .CellInfo cellInfo = 3;</code>
     */
    com.game.protocol.BagProtocol.CellInfo getCellInfo(int index);
    /**
     * <code>repeated .CellInfo cellInfo = 3;</code>
     */
    int getCellInfoCount();
    /**
     * <code>repeated .CellInfo cellInfo = 3;</code>
     */
    java.util.List<? extends com.game.protocol.BagProtocol.CellInfoOrBuilder> 
        getCellInfoOrBuilderList();
    /**
     * <code>repeated .CellInfo cellInfo = 3;</code>
     */
    com.game.protocol.BagProtocol.CellInfoOrBuilder getCellInfoOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 背包信息
   * </pre>
   *
   * Protobuf type {@code BagInfo}
   */
  public  static final class BagInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BagInfo)
      BagInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BagInfo.newBuilder() to construct.
    private BagInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BagInfo() {
      bagName_ = "";
      cellInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BagInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BagInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              bagId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              bagName_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                cellInfo_ = new java.util.ArrayList<com.game.protocol.BagProtocol.CellInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              cellInfo_.add(
                  input.readMessage(com.game.protocol.BagProtocol.CellInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          cellInfo_ = java.util.Collections.unmodifiableList(cellInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.protocol.BagProtocol.internal_static_BagInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.protocol.BagProtocol.internal_static_BagInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.protocol.BagProtocol.BagInfo.class, com.game.protocol.BagProtocol.BagInfo.Builder.class);
    }

    public static final int BAGID_FIELD_NUMBER = 1;
    private int bagId_;
    /**
     * <code>int32 bagId = 1;</code>
     * @return The bagId.
     */
    public int getBagId() {
      return bagId_;
    }

    public static final int BAGNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object bagName_;
    /**
     * <code>string bagName = 2;</code>
     * @return The bagName.
     */
    public java.lang.String getBagName() {
      java.lang.Object ref = bagName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bagName_ = s;
        return s;
      }
    }
    /**
     * <code>string bagName = 2;</code>
     * @return The bytes for bagName.
     */
    public com.google.protobuf.ByteString
        getBagNameBytes() {
      java.lang.Object ref = bagName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bagName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CELLINFO_FIELD_NUMBER = 3;
    private java.util.List<com.game.protocol.BagProtocol.CellInfo> cellInfo_;
    /**
     * <code>repeated .CellInfo cellInfo = 3;</code>
     */
    public java.util.List<com.game.protocol.BagProtocol.CellInfo> getCellInfoList() {
      return cellInfo_;
    }
    /**
     * <code>repeated .CellInfo cellInfo = 3;</code>
     */
    public java.util.List<? extends com.game.protocol.BagProtocol.CellInfoOrBuilder> 
        getCellInfoOrBuilderList() {
      return cellInfo_;
    }
    /**
     * <code>repeated .CellInfo cellInfo = 3;</code>
     */
    public int getCellInfoCount() {
      return cellInfo_.size();
    }
    /**
     * <code>repeated .CellInfo cellInfo = 3;</code>
     */
    public com.game.protocol.BagProtocol.CellInfo getCellInfo(int index) {
      return cellInfo_.get(index);
    }
    /**
     * <code>repeated .CellInfo cellInfo = 3;</code>
     */
    public com.game.protocol.BagProtocol.CellInfoOrBuilder getCellInfoOrBuilder(
        int index) {
      return cellInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bagId_ != 0) {
        output.writeInt32(1, bagId_);
      }
      if (!getBagNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bagName_);
      }
      for (int i = 0; i < cellInfo_.size(); i++) {
        output.writeMessage(3, cellInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bagId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bagId_);
      }
      if (!getBagNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bagName_);
      }
      for (int i = 0; i < cellInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, cellInfo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.protocol.BagProtocol.BagInfo)) {
        return super.equals(obj);
      }
      com.game.protocol.BagProtocol.BagInfo other = (com.game.protocol.BagProtocol.BagInfo) obj;

      if (getBagId()
          != other.getBagId()) return false;
      if (!getBagName()
          .equals(other.getBagName())) return false;
      if (!getCellInfoList()
          .equals(other.getCellInfoList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BAGID_FIELD_NUMBER;
      hash = (53 * hash) + getBagId();
      hash = (37 * hash) + BAGNAME_FIELD_NUMBER;
      hash = (53 * hash) + getBagName().hashCode();
      if (getCellInfoCount() > 0) {
        hash = (37 * hash) + CELLINFO_FIELD_NUMBER;
        hash = (53 * hash) + getCellInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.protocol.BagProtocol.BagInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.BagProtocol.BagInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.BagInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.BagProtocol.BagInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.BagInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.BagProtocol.BagInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.BagInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.BagProtocol.BagInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.BagInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.protocol.BagProtocol.BagInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.BagInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.BagProtocol.BagInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.protocol.BagProtocol.BagInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 背包信息
     * </pre>
     *
     * Protobuf type {@code BagInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BagInfo)
        com.game.protocol.BagProtocol.BagInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.protocol.BagProtocol.internal_static_BagInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.protocol.BagProtocol.internal_static_BagInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.protocol.BagProtocol.BagInfo.class, com.game.protocol.BagProtocol.BagInfo.Builder.class);
      }

      // Construct using com.game.protocol.BagProtocol.BagInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCellInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bagId_ = 0;

        bagName_ = "";

        if (cellInfoBuilder_ == null) {
          cellInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          cellInfoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.protocol.BagProtocol.internal_static_BagInfo_descriptor;
      }

      @java.lang.Override
      public com.game.protocol.BagProtocol.BagInfo getDefaultInstanceForType() {
        return com.game.protocol.BagProtocol.BagInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.protocol.BagProtocol.BagInfo build() {
        com.game.protocol.BagProtocol.BagInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.protocol.BagProtocol.BagInfo buildPartial() {
        com.game.protocol.BagProtocol.BagInfo result = new com.game.protocol.BagProtocol.BagInfo(this);
        int from_bitField0_ = bitField0_;
        result.bagId_ = bagId_;
        result.bagName_ = bagName_;
        if (cellInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            cellInfo_ = java.util.Collections.unmodifiableList(cellInfo_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.cellInfo_ = cellInfo_;
        } else {
          result.cellInfo_ = cellInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.protocol.BagProtocol.BagInfo) {
          return mergeFrom((com.game.protocol.BagProtocol.BagInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.protocol.BagProtocol.BagInfo other) {
        if (other == com.game.protocol.BagProtocol.BagInfo.getDefaultInstance()) return this;
        if (other.getBagId() != 0) {
          setBagId(other.getBagId());
        }
        if (!other.getBagName().isEmpty()) {
          bagName_ = other.bagName_;
          onChanged();
        }
        if (cellInfoBuilder_ == null) {
          if (!other.cellInfo_.isEmpty()) {
            if (cellInfo_.isEmpty()) {
              cellInfo_ = other.cellInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCellInfoIsMutable();
              cellInfo_.addAll(other.cellInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.cellInfo_.isEmpty()) {
            if (cellInfoBuilder_.isEmpty()) {
              cellInfoBuilder_.dispose();
              cellInfoBuilder_ = null;
              cellInfo_ = other.cellInfo_;
              bitField0_ = (bitField0_ & ~0x00000001);
              cellInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCellInfoFieldBuilder() : null;
            } else {
              cellInfoBuilder_.addAllMessages(other.cellInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.protocol.BagProtocol.BagInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.protocol.BagProtocol.BagInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int bagId_ ;
      /**
       * <code>int32 bagId = 1;</code>
       * @return The bagId.
       */
      public int getBagId() {
        return bagId_;
      }
      /**
       * <code>int32 bagId = 1;</code>
       * @param value The bagId to set.
       * @return This builder for chaining.
       */
      public Builder setBagId(int value) {
        
        bagId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bagId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBagId() {
        
        bagId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object bagName_ = "";
      /**
       * <code>string bagName = 2;</code>
       * @return The bagName.
       */
      public java.lang.String getBagName() {
        java.lang.Object ref = bagName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bagName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bagName = 2;</code>
       * @return The bytes for bagName.
       */
      public com.google.protobuf.ByteString
          getBagNameBytes() {
        java.lang.Object ref = bagName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bagName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bagName = 2;</code>
       * @param value The bagName to set.
       * @return This builder for chaining.
       */
      public Builder setBagName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bagName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bagName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBagName() {
        
        bagName_ = getDefaultInstance().getBagName();
        onChanged();
        return this;
      }
      /**
       * <code>string bagName = 2;</code>
       * @param value The bytes for bagName to set.
       * @return This builder for chaining.
       */
      public Builder setBagNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bagName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.game.protocol.BagProtocol.CellInfo> cellInfo_ =
        java.util.Collections.emptyList();
      private void ensureCellInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          cellInfo_ = new java.util.ArrayList<com.game.protocol.BagProtocol.CellInfo>(cellInfo_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.game.protocol.BagProtocol.CellInfo, com.game.protocol.BagProtocol.CellInfo.Builder, com.game.protocol.BagProtocol.CellInfoOrBuilder> cellInfoBuilder_;

      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public java.util.List<com.game.protocol.BagProtocol.CellInfo> getCellInfoList() {
        if (cellInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cellInfo_);
        } else {
          return cellInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public int getCellInfoCount() {
        if (cellInfoBuilder_ == null) {
          return cellInfo_.size();
        } else {
          return cellInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public com.game.protocol.BagProtocol.CellInfo getCellInfo(int index) {
        if (cellInfoBuilder_ == null) {
          return cellInfo_.get(index);
        } else {
          return cellInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public Builder setCellInfo(
          int index, com.game.protocol.BagProtocol.CellInfo value) {
        if (cellInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellInfoIsMutable();
          cellInfo_.set(index, value);
          onChanged();
        } else {
          cellInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public Builder setCellInfo(
          int index, com.game.protocol.BagProtocol.CellInfo.Builder builderForValue) {
        if (cellInfoBuilder_ == null) {
          ensureCellInfoIsMutable();
          cellInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          cellInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public Builder addCellInfo(com.game.protocol.BagProtocol.CellInfo value) {
        if (cellInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellInfoIsMutable();
          cellInfo_.add(value);
          onChanged();
        } else {
          cellInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public Builder addCellInfo(
          int index, com.game.protocol.BagProtocol.CellInfo value) {
        if (cellInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellInfoIsMutable();
          cellInfo_.add(index, value);
          onChanged();
        } else {
          cellInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public Builder addCellInfo(
          com.game.protocol.BagProtocol.CellInfo.Builder builderForValue) {
        if (cellInfoBuilder_ == null) {
          ensureCellInfoIsMutable();
          cellInfo_.add(builderForValue.build());
          onChanged();
        } else {
          cellInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public Builder addCellInfo(
          int index, com.game.protocol.BagProtocol.CellInfo.Builder builderForValue) {
        if (cellInfoBuilder_ == null) {
          ensureCellInfoIsMutable();
          cellInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          cellInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public Builder addAllCellInfo(
          java.lang.Iterable<? extends com.game.protocol.BagProtocol.CellInfo> values) {
        if (cellInfoBuilder_ == null) {
          ensureCellInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cellInfo_);
          onChanged();
        } else {
          cellInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public Builder clearCellInfo() {
        if (cellInfoBuilder_ == null) {
          cellInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          cellInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public Builder removeCellInfo(int index) {
        if (cellInfoBuilder_ == null) {
          ensureCellInfoIsMutable();
          cellInfo_.remove(index);
          onChanged();
        } else {
          cellInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public com.game.protocol.BagProtocol.CellInfo.Builder getCellInfoBuilder(
          int index) {
        return getCellInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public com.game.protocol.BagProtocol.CellInfoOrBuilder getCellInfoOrBuilder(
          int index) {
        if (cellInfoBuilder_ == null) {
          return cellInfo_.get(index);  } else {
          return cellInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public java.util.List<? extends com.game.protocol.BagProtocol.CellInfoOrBuilder> 
           getCellInfoOrBuilderList() {
        if (cellInfoBuilder_ != null) {
          return cellInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cellInfo_);
        }
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public com.game.protocol.BagProtocol.CellInfo.Builder addCellInfoBuilder() {
        return getCellInfoFieldBuilder().addBuilder(
            com.game.protocol.BagProtocol.CellInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public com.game.protocol.BagProtocol.CellInfo.Builder addCellInfoBuilder(
          int index) {
        return getCellInfoFieldBuilder().addBuilder(
            index, com.game.protocol.BagProtocol.CellInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .CellInfo cellInfo = 3;</code>
       */
      public java.util.List<com.game.protocol.BagProtocol.CellInfo.Builder> 
           getCellInfoBuilderList() {
        return getCellInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.game.protocol.BagProtocol.CellInfo, com.game.protocol.BagProtocol.CellInfo.Builder, com.game.protocol.BagProtocol.CellInfoOrBuilder> 
          getCellInfoFieldBuilder() {
        if (cellInfoBuilder_ == null) {
          cellInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.game.protocol.BagProtocol.CellInfo, com.game.protocol.BagProtocol.CellInfo.Builder, com.game.protocol.BagProtocol.CellInfoOrBuilder>(
                  cellInfo_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          cellInfo_ = null;
        }
        return cellInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BagInfo)
    }

    // @@protoc_insertion_point(class_scope:BagInfo)
    private static final com.game.protocol.BagProtocol.BagInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.protocol.BagProtocol.BagInfo();
    }

    public static com.game.protocol.BagProtocol.BagInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BagInfo>
        PARSER = new com.google.protobuf.AbstractParser<BagInfo>() {
      @java.lang.Override
      public BagInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BagInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BagInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BagInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.protocol.BagProtocol.BagInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CellInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CellInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string itemName = 2;</code>
     * @return The itemName.
     */
    java.lang.String getItemName();
    /**
     * <code>string itemName = 2;</code>
     * @return The bytes for itemName.
     */
    com.google.protobuf.ByteString
        getItemNameBytes();

    /**
     * <code>int32 itemType = 3;</code>
     * @return The itemType.
     */
    int getItemType();

    /**
     * <code>int32 itemCount = 4;</code>
     * @return The itemCount.
     */
    int getItemCount();

    /**
     * <code>int32 bagIndex = 5;</code>
     * @return The bagIndex.
     */
    int getBagIndex();
  }
  /**
   * <pre>
   * 格子信息（只包含简单信息）
   * </pre>
   *
   * Protobuf type {@code CellInfo}
   */
  public  static final class CellInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CellInfo)
      CellInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CellInfo.newBuilder() to construct.
    private CellInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CellInfo() {
      itemName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CellInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CellInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              itemName_ = s;
              break;
            }
            case 24: {

              itemType_ = input.readInt32();
              break;
            }
            case 32: {

              itemCount_ = input.readInt32();
              break;
            }
            case 40: {

              bagIndex_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.protocol.BagProtocol.internal_static_CellInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.protocol.BagProtocol.internal_static_CellInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.protocol.BagProtocol.CellInfo.class, com.game.protocol.BagProtocol.CellInfo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int ITEMNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object itemName_;
    /**
     * <code>string itemName = 2;</code>
     * @return The itemName.
     */
    public java.lang.String getItemName() {
      java.lang.Object ref = itemName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemName_ = s;
        return s;
      }
    }
    /**
     * <code>string itemName = 2;</code>
     * @return The bytes for itemName.
     */
    public com.google.protobuf.ByteString
        getItemNameBytes() {
      java.lang.Object ref = itemName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ITEMTYPE_FIELD_NUMBER = 3;
    private int itemType_;
    /**
     * <code>int32 itemType = 3;</code>
     * @return The itemType.
     */
    public int getItemType() {
      return itemType_;
    }

    public static final int ITEMCOUNT_FIELD_NUMBER = 4;
    private int itemCount_;
    /**
     * <code>int32 itemCount = 4;</code>
     * @return The itemCount.
     */
    public int getItemCount() {
      return itemCount_;
    }

    public static final int BAGINDEX_FIELD_NUMBER = 5;
    private int bagIndex_;
    /**
     * <code>int32 bagIndex = 5;</code>
     * @return The bagIndex.
     */
    public int getBagIndex() {
      return bagIndex_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getItemNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, itemName_);
      }
      if (itemType_ != 0) {
        output.writeInt32(3, itemType_);
      }
      if (itemCount_ != 0) {
        output.writeInt32(4, itemCount_);
      }
      if (bagIndex_ != 0) {
        output.writeInt32(5, bagIndex_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getItemNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, itemName_);
      }
      if (itemType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, itemType_);
      }
      if (itemCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, itemCount_);
      }
      if (bagIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, bagIndex_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.protocol.BagProtocol.CellInfo)) {
        return super.equals(obj);
      }
      com.game.protocol.BagProtocol.CellInfo other = (com.game.protocol.BagProtocol.CellInfo) obj;

      if (getId()
          != other.getId()) return false;
      if (!getItemName()
          .equals(other.getItemName())) return false;
      if (getItemType()
          != other.getItemType()) return false;
      if (getItemCount()
          != other.getItemCount()) return false;
      if (getBagIndex()
          != other.getBagIndex()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + ITEMNAME_FIELD_NUMBER;
      hash = (53 * hash) + getItemName().hashCode();
      hash = (37 * hash) + ITEMTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getItemType();
      hash = (37 * hash) + ITEMCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getItemCount();
      hash = (37 * hash) + BAGINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getBagIndex();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.protocol.BagProtocol.CellInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.BagProtocol.CellInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.CellInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.BagProtocol.CellInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.CellInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.BagProtocol.CellInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.CellInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.BagProtocol.CellInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.CellInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.protocol.BagProtocol.CellInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.BagProtocol.CellInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.BagProtocol.CellInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.protocol.BagProtocol.CellInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 格子信息（只包含简单信息）
     * </pre>
     *
     * Protobuf type {@code CellInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CellInfo)
        com.game.protocol.BagProtocol.CellInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.protocol.BagProtocol.internal_static_CellInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.protocol.BagProtocol.internal_static_CellInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.protocol.BagProtocol.CellInfo.class, com.game.protocol.BagProtocol.CellInfo.Builder.class);
      }

      // Construct using com.game.protocol.BagProtocol.CellInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        itemName_ = "";

        itemType_ = 0;

        itemCount_ = 0;

        bagIndex_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.protocol.BagProtocol.internal_static_CellInfo_descriptor;
      }

      @java.lang.Override
      public com.game.protocol.BagProtocol.CellInfo getDefaultInstanceForType() {
        return com.game.protocol.BagProtocol.CellInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.protocol.BagProtocol.CellInfo build() {
        com.game.protocol.BagProtocol.CellInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.protocol.BagProtocol.CellInfo buildPartial() {
        com.game.protocol.BagProtocol.CellInfo result = new com.game.protocol.BagProtocol.CellInfo(this);
        result.id_ = id_;
        result.itemName_ = itemName_;
        result.itemType_ = itemType_;
        result.itemCount_ = itemCount_;
        result.bagIndex_ = bagIndex_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.protocol.BagProtocol.CellInfo) {
          return mergeFrom((com.game.protocol.BagProtocol.CellInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.protocol.BagProtocol.CellInfo other) {
        if (other == com.game.protocol.BagProtocol.CellInfo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getItemName().isEmpty()) {
          itemName_ = other.itemName_;
          onChanged();
        }
        if (other.getItemType() != 0) {
          setItemType(other.getItemType());
        }
        if (other.getItemCount() != 0) {
          setItemCount(other.getItemCount());
        }
        if (other.getBagIndex() != 0) {
          setBagIndex(other.getBagIndex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.protocol.BagProtocol.CellInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.protocol.BagProtocol.CellInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object itemName_ = "";
      /**
       * <code>string itemName = 2;</code>
       * @return The itemName.
       */
      public java.lang.String getItemName() {
        java.lang.Object ref = itemName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          itemName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string itemName = 2;</code>
       * @return The bytes for itemName.
       */
      public com.google.protobuf.ByteString
          getItemNameBytes() {
        java.lang.Object ref = itemName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string itemName = 2;</code>
       * @param value The itemName to set.
       * @return This builder for chaining.
       */
      public Builder setItemName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        itemName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string itemName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearItemName() {
        
        itemName_ = getDefaultInstance().getItemName();
        onChanged();
        return this;
      }
      /**
       * <code>string itemName = 2;</code>
       * @param value The bytes for itemName to set.
       * @return This builder for chaining.
       */
      public Builder setItemNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        itemName_ = value;
        onChanged();
        return this;
      }

      private int itemType_ ;
      /**
       * <code>int32 itemType = 3;</code>
       * @return The itemType.
       */
      public int getItemType() {
        return itemType_;
      }
      /**
       * <code>int32 itemType = 3;</code>
       * @param value The itemType to set.
       * @return This builder for chaining.
       */
      public Builder setItemType(int value) {
        
        itemType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 itemType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearItemType() {
        
        itemType_ = 0;
        onChanged();
        return this;
      }

      private int itemCount_ ;
      /**
       * <code>int32 itemCount = 4;</code>
       * @return The itemCount.
       */
      public int getItemCount() {
        return itemCount_;
      }
      /**
       * <code>int32 itemCount = 4;</code>
       * @param value The itemCount to set.
       * @return This builder for chaining.
       */
      public Builder setItemCount(int value) {
        
        itemCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 itemCount = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearItemCount() {
        
        itemCount_ = 0;
        onChanged();
        return this;
      }

      private int bagIndex_ ;
      /**
       * <code>int32 bagIndex = 5;</code>
       * @return The bagIndex.
       */
      public int getBagIndex() {
        return bagIndex_;
      }
      /**
       * <code>int32 bagIndex = 5;</code>
       * @param value The bagIndex to set.
       * @return This builder for chaining.
       */
      public Builder setBagIndex(int value) {
        
        bagIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bagIndex = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBagIndex() {
        
        bagIndex_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CellInfo)
    }

    // @@protoc_insertion_point(class_scope:CellInfo)
    private static final com.game.protocol.BagProtocol.CellInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.protocol.BagProtocol.CellInfo();
    }

    public static com.game.protocol.BagProtocol.CellInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CellInfo>
        PARSER = new com.google.protobuf.AbstractParser<CellInfo>() {
      @java.lang.Override
      public CellInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CellInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CellInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CellInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.protocol.BagProtocol.CellInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenBag_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenBag_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BagInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BagInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CellInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CellInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tBag.proto\"\030\n\007OpenBag\022\r\n\005bagId\030\001 \001(\005\"F\n" +
      "\007BagInfo\022\r\n\005bagId\030\001 \001(\005\022\017\n\007bagName\030\002 \001(\t" +
      "\022\033\n\010cellInfo\030\003 \003(\0132\t.CellInfo\"_\n\010CellInf" +
      "o\022\n\n\002id\030\001 \001(\005\022\020\n\010itemName\030\002 \001(\t\022\020\n\010itemT" +
      "ype\030\003 \001(\005\022\021\n\titemCount\030\004 \001(\005\022\020\n\010bagIndex" +
      "\030\005 \001(\005B \n\021com.game.protocolB\013BagProtocol" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OpenBag_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OpenBag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenBag_descriptor,
        new java.lang.String[] { "BagId", });
    internal_static_BagInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BagInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BagInfo_descriptor,
        new java.lang.String[] { "BagId", "BagName", "CellInfo", });
    internal_static_CellInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CellInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CellInfo_descriptor,
        new java.lang.String[] { "Id", "ItemName", "ItemType", "ItemCount", "BagIndex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
