// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Skill.proto

package com.game.protocol;

public final class SkillProtocol {
  private SkillProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SkillBarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SkillBar)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Skill skills = 1;</code>
     */
    java.util.List<com.game.protocol.SkillProtocol.Skill> 
        getSkillsList();
    /**
     * <code>repeated .Skill skills = 1;</code>
     */
    com.game.protocol.SkillProtocol.Skill getSkills(int index);
    /**
     * <code>repeated .Skill skills = 1;</code>
     */
    int getSkillsCount();
    /**
     * <code>repeated .Skill skills = 1;</code>
     */
    java.util.List<? extends com.game.protocol.SkillProtocol.SkillOrBuilder> 
        getSkillsOrBuilderList();
    /**
     * <code>repeated .Skill skills = 1;</code>
     */
    com.game.protocol.SkillProtocol.SkillOrBuilder getSkillsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code SkillBar}
   */
  public  static final class SkillBar extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SkillBar)
      SkillBarOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SkillBar.newBuilder() to construct.
    private SkillBar(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SkillBar() {
      skills_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SkillBar();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SkillBar(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                skills_ = new java.util.ArrayList<com.game.protocol.SkillProtocol.Skill>();
                mutable_bitField0_ |= 0x00000001;
              }
              skills_.add(
                  input.readMessage(com.game.protocol.SkillProtocol.Skill.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          skills_ = java.util.Collections.unmodifiableList(skills_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.protocol.SkillProtocol.internal_static_SkillBar_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.protocol.SkillProtocol.internal_static_SkillBar_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.protocol.SkillProtocol.SkillBar.class, com.game.protocol.SkillProtocol.SkillBar.Builder.class);
    }

    public static final int SKILLS_FIELD_NUMBER = 1;
    private java.util.List<com.game.protocol.SkillProtocol.Skill> skills_;
    /**
     * <code>repeated .Skill skills = 1;</code>
     */
    public java.util.List<com.game.protocol.SkillProtocol.Skill> getSkillsList() {
      return skills_;
    }
    /**
     * <code>repeated .Skill skills = 1;</code>
     */
    public java.util.List<? extends com.game.protocol.SkillProtocol.SkillOrBuilder> 
        getSkillsOrBuilderList() {
      return skills_;
    }
    /**
     * <code>repeated .Skill skills = 1;</code>
     */
    public int getSkillsCount() {
      return skills_.size();
    }
    /**
     * <code>repeated .Skill skills = 1;</code>
     */
    public com.game.protocol.SkillProtocol.Skill getSkills(int index) {
      return skills_.get(index);
    }
    /**
     * <code>repeated .Skill skills = 1;</code>
     */
    public com.game.protocol.SkillProtocol.SkillOrBuilder getSkillsOrBuilder(
        int index) {
      return skills_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < skills_.size(); i++) {
        output.writeMessage(1, skills_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < skills_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, skills_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.protocol.SkillProtocol.SkillBar)) {
        return super.equals(obj);
      }
      com.game.protocol.SkillProtocol.SkillBar other = (com.game.protocol.SkillProtocol.SkillBar) obj;

      if (!getSkillsList()
          .equals(other.getSkillsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSkillsCount() > 0) {
        hash = (37 * hash) + SKILLS_FIELD_NUMBER;
        hash = (53 * hash) + getSkillsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.protocol.SkillProtocol.SkillBar parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.SkillProtocol.SkillBar parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.SkillProtocol.SkillBar parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.SkillProtocol.SkillBar parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.SkillProtocol.SkillBar parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.SkillProtocol.SkillBar parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.SkillProtocol.SkillBar parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.SkillProtocol.SkillBar parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.SkillProtocol.SkillBar parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.protocol.SkillProtocol.SkillBar parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.SkillProtocol.SkillBar parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.SkillProtocol.SkillBar parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.protocol.SkillProtocol.SkillBar prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SkillBar}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SkillBar)
        com.game.protocol.SkillProtocol.SkillBarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.protocol.SkillProtocol.internal_static_SkillBar_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.protocol.SkillProtocol.internal_static_SkillBar_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.protocol.SkillProtocol.SkillBar.class, com.game.protocol.SkillProtocol.SkillBar.Builder.class);
      }

      // Construct using com.game.protocol.SkillProtocol.SkillBar.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSkillsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (skillsBuilder_ == null) {
          skills_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          skillsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.protocol.SkillProtocol.internal_static_SkillBar_descriptor;
      }

      @java.lang.Override
      public com.game.protocol.SkillProtocol.SkillBar getDefaultInstanceForType() {
        return com.game.protocol.SkillProtocol.SkillBar.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.protocol.SkillProtocol.SkillBar build() {
        com.game.protocol.SkillProtocol.SkillBar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.protocol.SkillProtocol.SkillBar buildPartial() {
        com.game.protocol.SkillProtocol.SkillBar result = new com.game.protocol.SkillProtocol.SkillBar(this);
        int from_bitField0_ = bitField0_;
        if (skillsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            skills_ = java.util.Collections.unmodifiableList(skills_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.skills_ = skills_;
        } else {
          result.skills_ = skillsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.protocol.SkillProtocol.SkillBar) {
          return mergeFrom((com.game.protocol.SkillProtocol.SkillBar)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.protocol.SkillProtocol.SkillBar other) {
        if (other == com.game.protocol.SkillProtocol.SkillBar.getDefaultInstance()) return this;
        if (skillsBuilder_ == null) {
          if (!other.skills_.isEmpty()) {
            if (skills_.isEmpty()) {
              skills_ = other.skills_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSkillsIsMutable();
              skills_.addAll(other.skills_);
            }
            onChanged();
          }
        } else {
          if (!other.skills_.isEmpty()) {
            if (skillsBuilder_.isEmpty()) {
              skillsBuilder_.dispose();
              skillsBuilder_ = null;
              skills_ = other.skills_;
              bitField0_ = (bitField0_ & ~0x00000001);
              skillsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSkillsFieldBuilder() : null;
            } else {
              skillsBuilder_.addAllMessages(other.skills_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.protocol.SkillProtocol.SkillBar parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.protocol.SkillProtocol.SkillBar) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.game.protocol.SkillProtocol.Skill> skills_ =
        java.util.Collections.emptyList();
      private void ensureSkillsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          skills_ = new java.util.ArrayList<com.game.protocol.SkillProtocol.Skill>(skills_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.game.protocol.SkillProtocol.Skill, com.game.protocol.SkillProtocol.Skill.Builder, com.game.protocol.SkillProtocol.SkillOrBuilder> skillsBuilder_;

      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public java.util.List<com.game.protocol.SkillProtocol.Skill> getSkillsList() {
        if (skillsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(skills_);
        } else {
          return skillsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public int getSkillsCount() {
        if (skillsBuilder_ == null) {
          return skills_.size();
        } else {
          return skillsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public com.game.protocol.SkillProtocol.Skill getSkills(int index) {
        if (skillsBuilder_ == null) {
          return skills_.get(index);
        } else {
          return skillsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public Builder setSkills(
          int index, com.game.protocol.SkillProtocol.Skill value) {
        if (skillsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSkillsIsMutable();
          skills_.set(index, value);
          onChanged();
        } else {
          skillsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public Builder setSkills(
          int index, com.game.protocol.SkillProtocol.Skill.Builder builderForValue) {
        if (skillsBuilder_ == null) {
          ensureSkillsIsMutable();
          skills_.set(index, builderForValue.build());
          onChanged();
        } else {
          skillsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public Builder addSkills(com.game.protocol.SkillProtocol.Skill value) {
        if (skillsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSkillsIsMutable();
          skills_.add(value);
          onChanged();
        } else {
          skillsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public Builder addSkills(
          int index, com.game.protocol.SkillProtocol.Skill value) {
        if (skillsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSkillsIsMutable();
          skills_.add(index, value);
          onChanged();
        } else {
          skillsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public Builder addSkills(
          com.game.protocol.SkillProtocol.Skill.Builder builderForValue) {
        if (skillsBuilder_ == null) {
          ensureSkillsIsMutable();
          skills_.add(builderForValue.build());
          onChanged();
        } else {
          skillsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public Builder addSkills(
          int index, com.game.protocol.SkillProtocol.Skill.Builder builderForValue) {
        if (skillsBuilder_ == null) {
          ensureSkillsIsMutable();
          skills_.add(index, builderForValue.build());
          onChanged();
        } else {
          skillsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public Builder addAllSkills(
          java.lang.Iterable<? extends com.game.protocol.SkillProtocol.Skill> values) {
        if (skillsBuilder_ == null) {
          ensureSkillsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, skills_);
          onChanged();
        } else {
          skillsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public Builder clearSkills() {
        if (skillsBuilder_ == null) {
          skills_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          skillsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public Builder removeSkills(int index) {
        if (skillsBuilder_ == null) {
          ensureSkillsIsMutable();
          skills_.remove(index);
          onChanged();
        } else {
          skillsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public com.game.protocol.SkillProtocol.Skill.Builder getSkillsBuilder(
          int index) {
        return getSkillsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public com.game.protocol.SkillProtocol.SkillOrBuilder getSkillsOrBuilder(
          int index) {
        if (skillsBuilder_ == null) {
          return skills_.get(index);  } else {
          return skillsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public java.util.List<? extends com.game.protocol.SkillProtocol.SkillOrBuilder> 
           getSkillsOrBuilderList() {
        if (skillsBuilder_ != null) {
          return skillsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(skills_);
        }
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public com.game.protocol.SkillProtocol.Skill.Builder addSkillsBuilder() {
        return getSkillsFieldBuilder().addBuilder(
            com.game.protocol.SkillProtocol.Skill.getDefaultInstance());
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public com.game.protocol.SkillProtocol.Skill.Builder addSkillsBuilder(
          int index) {
        return getSkillsFieldBuilder().addBuilder(
            index, com.game.protocol.SkillProtocol.Skill.getDefaultInstance());
      }
      /**
       * <code>repeated .Skill skills = 1;</code>
       */
      public java.util.List<com.game.protocol.SkillProtocol.Skill.Builder> 
           getSkillsBuilderList() {
        return getSkillsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.game.protocol.SkillProtocol.Skill, com.game.protocol.SkillProtocol.Skill.Builder, com.game.protocol.SkillProtocol.SkillOrBuilder> 
          getSkillsFieldBuilder() {
        if (skillsBuilder_ == null) {
          skillsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.game.protocol.SkillProtocol.Skill, com.game.protocol.SkillProtocol.Skill.Builder, com.game.protocol.SkillProtocol.SkillOrBuilder>(
                  skills_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          skills_ = null;
        }
        return skillsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SkillBar)
    }

    // @@protoc_insertion_point(class_scope:SkillBar)
    private static final com.game.protocol.SkillProtocol.SkillBar DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.protocol.SkillProtocol.SkillBar();
    }

    public static com.game.protocol.SkillProtocol.SkillBar getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SkillBar>
        PARSER = new com.google.protobuf.AbstractParser<SkillBar>() {
      @java.lang.Override
      public SkillBar parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SkillBar(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SkillBar> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SkillBar> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.protocol.SkillProtocol.SkillBar getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SkillOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Skill)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 career = 3;</code>
     * @return The career.
     */
    int getCareer();

    /**
     * <code>int32 level = 4;</code>
     * @return The level.
     */
    int getLevel();

    /**
     * <code>string formula = 5;</code>
     * @return The formula.
     */
    java.lang.String getFormula();
    /**
     * <code>string formula = 5;</code>
     * @return The bytes for formula.
     */
    com.google.protobuf.ByteString
        getFormulaBytes();

    /**
     * <code>int32 consume = 6;</code>
     * @return The consume.
     */
    int getConsume();

    /**
     * <code>string desc = 7;</code>
     * @return The desc.
     */
    java.lang.String getDesc();
    /**
     * <code>string desc = 7;</code>
     * @return The bytes for desc.
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>int32 bagIndex = 8;</code>
     * @return The bagIndex.
     */
    int getBagIndex();

    /**
     * <code>int32 coolTimeResidue = 9;</code>
     * @return The coolTimeResidue.
     */
    int getCoolTimeResidue();

    /**
     * <code>int32 state = 10;</code>
     * @return The state.
     */
    int getState();
  }
  /**
   * Protobuf type {@code Skill}
   */
  public  static final class Skill extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Skill)
      SkillOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Skill.newBuilder() to construct.
    private Skill(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Skill() {
      name_ = "";
      formula_ = "";
      desc_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Skill();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Skill(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              career_ = input.readInt32();
              break;
            }
            case 32: {

              level_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              formula_ = s;
              break;
            }
            case 48: {

              consume_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 64: {

              bagIndex_ = input.readInt32();
              break;
            }
            case 72: {

              coolTimeResidue_ = input.readInt32();
              break;
            }
            case 80: {

              state_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.game.protocol.SkillProtocol.internal_static_Skill_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.game.protocol.SkillProtocol.internal_static_Skill_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.game.protocol.SkillProtocol.Skill.class, com.game.protocol.SkillProtocol.Skill.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAREER_FIELD_NUMBER = 3;
    private int career_;
    /**
     * <code>int32 career = 3;</code>
     * @return The career.
     */
    public int getCareer() {
      return career_;
    }

    public static final int LEVEL_FIELD_NUMBER = 4;
    private int level_;
    /**
     * <code>int32 level = 4;</code>
     * @return The level.
     */
    public int getLevel() {
      return level_;
    }

    public static final int FORMULA_FIELD_NUMBER = 5;
    private volatile java.lang.Object formula_;
    /**
     * <code>string formula = 5;</code>
     * @return The formula.
     */
    public java.lang.String getFormula() {
      java.lang.Object ref = formula_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        formula_ = s;
        return s;
      }
    }
    /**
     * <code>string formula = 5;</code>
     * @return The bytes for formula.
     */
    public com.google.protobuf.ByteString
        getFormulaBytes() {
      java.lang.Object ref = formula_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        formula_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONSUME_FIELD_NUMBER = 6;
    private int consume_;
    /**
     * <code>int32 consume = 6;</code>
     * @return The consume.
     */
    public int getConsume() {
      return consume_;
    }

    public static final int DESC_FIELD_NUMBER = 7;
    private volatile java.lang.Object desc_;
    /**
     * <code>string desc = 7;</code>
     * @return The desc.
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>string desc = 7;</code>
     * @return The bytes for desc.
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BAGINDEX_FIELD_NUMBER = 8;
    private int bagIndex_;
    /**
     * <code>int32 bagIndex = 8;</code>
     * @return The bagIndex.
     */
    public int getBagIndex() {
      return bagIndex_;
    }

    public static final int COOLTIMERESIDUE_FIELD_NUMBER = 9;
    private int coolTimeResidue_;
    /**
     * <code>int32 coolTimeResidue = 9;</code>
     * @return The coolTimeResidue.
     */
    public int getCoolTimeResidue() {
      return coolTimeResidue_;
    }

    public static final int STATE_FIELD_NUMBER = 10;
    private int state_;
    /**
     * <code>int32 state = 10;</code>
     * @return The state.
     */
    public int getState() {
      return state_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (career_ != 0) {
        output.writeInt32(3, career_);
      }
      if (level_ != 0) {
        output.writeInt32(4, level_);
      }
      if (!getFormulaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, formula_);
      }
      if (consume_ != 0) {
        output.writeInt32(6, consume_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, desc_);
      }
      if (bagIndex_ != 0) {
        output.writeInt32(8, bagIndex_);
      }
      if (coolTimeResidue_ != 0) {
        output.writeInt32(9, coolTimeResidue_);
      }
      if (state_ != 0) {
        output.writeInt32(10, state_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (career_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, career_);
      }
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, level_);
      }
      if (!getFormulaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, formula_);
      }
      if (consume_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, consume_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, desc_);
      }
      if (bagIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, bagIndex_);
      }
      if (coolTimeResidue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, coolTimeResidue_);
      }
      if (state_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.game.protocol.SkillProtocol.Skill)) {
        return super.equals(obj);
      }
      com.game.protocol.SkillProtocol.Skill other = (com.game.protocol.SkillProtocol.Skill) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getCareer()
          != other.getCareer()) return false;
      if (getLevel()
          != other.getLevel()) return false;
      if (!getFormula()
          .equals(other.getFormula())) return false;
      if (getConsume()
          != other.getConsume()) return false;
      if (!getDesc()
          .equals(other.getDesc())) return false;
      if (getBagIndex()
          != other.getBagIndex()) return false;
      if (getCoolTimeResidue()
          != other.getCoolTimeResidue()) return false;
      if (getState()
          != other.getState()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + CAREER_FIELD_NUMBER;
      hash = (53 * hash) + getCareer();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (37 * hash) + FORMULA_FIELD_NUMBER;
      hash = (53 * hash) + getFormula().hashCode();
      hash = (37 * hash) + CONSUME_FIELD_NUMBER;
      hash = (53 * hash) + getConsume();
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      hash = (37 * hash) + BAGINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getBagIndex();
      hash = (37 * hash) + COOLTIMERESIDUE_FIELD_NUMBER;
      hash = (53 * hash) + getCoolTimeResidue();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.game.protocol.SkillProtocol.Skill parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.SkillProtocol.Skill parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.SkillProtocol.Skill parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.SkillProtocol.Skill parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.SkillProtocol.Skill parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.game.protocol.SkillProtocol.Skill parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.game.protocol.SkillProtocol.Skill parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.SkillProtocol.Skill parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.SkillProtocol.Skill parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.game.protocol.SkillProtocol.Skill parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.game.protocol.SkillProtocol.Skill parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.game.protocol.SkillProtocol.Skill parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.game.protocol.SkillProtocol.Skill prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Skill}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Skill)
        com.game.protocol.SkillProtocol.SkillOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.game.protocol.SkillProtocol.internal_static_Skill_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.game.protocol.SkillProtocol.internal_static_Skill_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.game.protocol.SkillProtocol.Skill.class, com.game.protocol.SkillProtocol.Skill.Builder.class);
      }

      // Construct using com.game.protocol.SkillProtocol.Skill.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        career_ = 0;

        level_ = 0;

        formula_ = "";

        consume_ = 0;

        desc_ = "";

        bagIndex_ = 0;

        coolTimeResidue_ = 0;

        state_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.game.protocol.SkillProtocol.internal_static_Skill_descriptor;
      }

      @java.lang.Override
      public com.game.protocol.SkillProtocol.Skill getDefaultInstanceForType() {
        return com.game.protocol.SkillProtocol.Skill.getDefaultInstance();
      }

      @java.lang.Override
      public com.game.protocol.SkillProtocol.Skill build() {
        com.game.protocol.SkillProtocol.Skill result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.game.protocol.SkillProtocol.Skill buildPartial() {
        com.game.protocol.SkillProtocol.Skill result = new com.game.protocol.SkillProtocol.Skill(this);
        result.id_ = id_;
        result.name_ = name_;
        result.career_ = career_;
        result.level_ = level_;
        result.formula_ = formula_;
        result.consume_ = consume_;
        result.desc_ = desc_;
        result.bagIndex_ = bagIndex_;
        result.coolTimeResidue_ = coolTimeResidue_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.game.protocol.SkillProtocol.Skill) {
          return mergeFrom((com.game.protocol.SkillProtocol.Skill)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.game.protocol.SkillProtocol.Skill other) {
        if (other == com.game.protocol.SkillProtocol.Skill.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getCareer() != 0) {
          setCareer(other.getCareer());
        }
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        if (!other.getFormula().isEmpty()) {
          formula_ = other.formula_;
          onChanged();
        }
        if (other.getConsume() != 0) {
          setConsume(other.getConsume());
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (other.getBagIndex() != 0) {
          setBagIndex(other.getBagIndex());
        }
        if (other.getCoolTimeResidue() != 0) {
          setCoolTimeResidue(other.getCoolTimeResidue());
        }
        if (other.getState() != 0) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.game.protocol.SkillProtocol.Skill parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.game.protocol.SkillProtocol.Skill) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int career_ ;
      /**
       * <code>int32 career = 3;</code>
       * @return The career.
       */
      public int getCareer() {
        return career_;
      }
      /**
       * <code>int32 career = 3;</code>
       * @param value The career to set.
       * @return This builder for chaining.
       */
      public Builder setCareer(int value) {
        
        career_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 career = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCareer() {
        
        career_ = 0;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>int32 level = 4;</code>
       * @return The level.
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>int32 level = 4;</code>
       * @param value The level to set.
       * @return This builder for chaining.
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 level = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object formula_ = "";
      /**
       * <code>string formula = 5;</code>
       * @return The formula.
       */
      public java.lang.String getFormula() {
        java.lang.Object ref = formula_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          formula_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string formula = 5;</code>
       * @return The bytes for formula.
       */
      public com.google.protobuf.ByteString
          getFormulaBytes() {
        java.lang.Object ref = formula_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          formula_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string formula = 5;</code>
       * @param value The formula to set.
       * @return This builder for chaining.
       */
      public Builder setFormula(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        formula_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string formula = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFormula() {
        
        formula_ = getDefaultInstance().getFormula();
        onChanged();
        return this;
      }
      /**
       * <code>string formula = 5;</code>
       * @param value The bytes for formula to set.
       * @return This builder for chaining.
       */
      public Builder setFormulaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        formula_ = value;
        onChanged();
        return this;
      }

      private int consume_ ;
      /**
       * <code>int32 consume = 6;</code>
       * @return The consume.
       */
      public int getConsume() {
        return consume_;
      }
      /**
       * <code>int32 consume = 6;</code>
       * @param value The consume to set.
       * @return This builder for chaining.
       */
      public Builder setConsume(int value) {
        
        consume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 consume = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearConsume() {
        
        consume_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>string desc = 7;</code>
       * @return The desc.
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string desc = 7;</code>
       * @return The bytes for desc.
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string desc = 7;</code>
       * @param value The desc to set.
       * @return This builder for chaining.
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 7;</code>
       * @param value The bytes for desc to set.
       * @return This builder for chaining.
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private int bagIndex_ ;
      /**
       * <code>int32 bagIndex = 8;</code>
       * @return The bagIndex.
       */
      public int getBagIndex() {
        return bagIndex_;
      }
      /**
       * <code>int32 bagIndex = 8;</code>
       * @param value The bagIndex to set.
       * @return This builder for chaining.
       */
      public Builder setBagIndex(int value) {
        
        bagIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bagIndex = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearBagIndex() {
        
        bagIndex_ = 0;
        onChanged();
        return this;
      }

      private int coolTimeResidue_ ;
      /**
       * <code>int32 coolTimeResidue = 9;</code>
       * @return The coolTimeResidue.
       */
      public int getCoolTimeResidue() {
        return coolTimeResidue_;
      }
      /**
       * <code>int32 coolTimeResidue = 9;</code>
       * @param value The coolTimeResidue to set.
       * @return This builder for chaining.
       */
      public Builder setCoolTimeResidue(int value) {
        
        coolTimeResidue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 coolTimeResidue = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearCoolTimeResidue() {
        
        coolTimeResidue_ = 0;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <code>int32 state = 10;</code>
       * @return The state.
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>int32 state = 10;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 state = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Skill)
    }

    // @@protoc_insertion_point(class_scope:Skill)
    private static final com.game.protocol.SkillProtocol.Skill DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.game.protocol.SkillProtocol.Skill();
    }

    public static com.game.protocol.SkillProtocol.Skill getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Skill>
        PARSER = new com.google.protobuf.AbstractParser<Skill>() {
      @java.lang.Override
      public Skill parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Skill(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Skill> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Skill> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.game.protocol.SkillProtocol.Skill getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SkillBar_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SkillBar_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Skill_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Skill_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Skill.proto\"\"\n\010SkillBar\022\026\n\006skills\030\001 \003(" +
      "\0132\006.Skill\"\252\001\n\005Skill\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030" +
      "\002 \001(\t\022\016\n\006career\030\003 \001(\005\022\r\n\005level\030\004 \001(\005\022\017\n\007" +
      "formula\030\005 \001(\t\022\017\n\007consume\030\006 \001(\005\022\014\n\004desc\030\007" +
      " \001(\t\022\020\n\010bagIndex\030\010 \001(\005\022\027\n\017coolTimeResidu" +
      "e\030\t \001(\005\022\r\n\005state\030\n \001(\005B\"\n\021com.game.proto" +
      "colB\rSkillProtocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SkillBar_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SkillBar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SkillBar_descriptor,
        new java.lang.String[] { "Skills", });
    internal_static_Skill_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Skill_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Skill_descriptor,
        new java.lang.String[] { "Id", "Name", "Career", "Level", "Formula", "Consume", "Desc", "BagIndex", "CoolTimeResidue", "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
